import { test, expect } from '@playwright/test';

test('boots into the 3D scene and opens the local desktop inside the monitor', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'START', exact: true })).toBeVisible();
  // The BIOS dialog fades in only after all scene resources have loaded.
  await page.waitForTimeout(2500);
  await page.getByRole('button', { name: 'START', exact: true }).click();
  await expect(page.getByText('Click anywhere to begin', { exact: true })).toBeVisible({ timeout: 15000 });
  await page.waitForTimeout(3000);
  await page.screenshot({ path: 'test-results/scene.png' });
  await page.mouse.click(450, 700);
  await page.waitForTimeout(2200);
  await page.mouse.move(720, 430);
  await page.waitForTimeout(2500);
  const desktop = page.frameLocator('#computer-screen');
  await desktop.getByRole('button', { name: 'About Connor', exact: true }).first().click();
  await expect(desktop.getByRole('dialog', { name: 'About Connor' })).toBeVisible();
  await expect(desktop.locator('.portrait')).toHaveJSProperty('complete', true);
  await page.mouse.move(730, 450);
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/monitor.png' });
  expect(errors).toEqual([]);
});

test('desktop apps, window controls, personalization and keyboard unlocking work', async ({ page }) => {
  await page.goto('/desktop.html');
  await page.getByRole('button', { name: 'About Connor', exact: true }).first().click();
  const about = page.getByRole('dialog', { name: 'About Connor' });
  await expect(about.getByRole('heading', { name: /my name is Connor Love/ })).toBeVisible();
  await about.getByRole('button', { name: 'Projects', exact: true }).click();
  await expect(about.locator('.projects a')).toHaveCount(3);
  await expect(about.locator('.projects a').first()).toHaveAttribute('href', 'https://www.connorlove.com/projects/honestui');
  await page.getByLabel('Minimize about', { exact: true }).click();
  await expect(about).toHaveCount(0);
  await page.getByRole('button', { name: 'About Connor', exact: true }).first().click();
  await expect(about).toBeVisible();
  await page.getByLabel('Maximize about', { exact: true }).click();
  await expect(about).toHaveClass(/maximized/);
  await page.getByLabel('Maximize about', { exact: true }).click();
  const before = await about.boundingBox();
  await page.mouse.move(before!.x + 200, before!.y + 16);
  await page.mouse.down();
  await page.mouse.move(before!.x + 250, before!.y + 66, { steps: 5 });
  await page.mouse.up();
  const after = await about.boundingBox();
  expect(after!.x).toBeGreaterThan(before!.x);
  await page.getByRole('button', { name: 'Terminal', exact: true }).click();
  await page.getByLabel('Terminal command').fill('whoami');
  await page.getByLabel('Terminal command').press('Enter');
  await expect(page.locator('.terminal pre').last()).toContainText('Connor Love');
  await page.getByRole('button', { name: 'Calculator', exact: true }).click();
  for (const key of ['7', '×', '6', '=']) await page.locator('.calc-keys').getByRole('button', { name: key, exact: true }).click();
  await expect(page.locator('output')).toHaveText('42');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'forest wallpaper' }).click();
  await expect(page.locator('.desktop')).toHaveClass('desktop forest');
  await page.getByRole('button', { name: 'Lock screen', exact: true }).click();
  await expect(page.locator('.lock-screen')).toBeVisible();
  await page.keyboard.press('Enter');
  await expect(page.locator('.lock-screen')).toHaveCount(0);
  await page.getByLabel('Close settings', { exact: true }).click();
  await page.getByLabel('Close calculator', { exact: true }).click();
  await page.getByLabel('Close terminal', { exact: true }).click();
  await about.getByRole('button', { name: 'Contact', exact: true }).click();
  await expect(page.getByLabel('To', { exact: true })).toHaveValue('loveconnor2005@gmail.com');
  await page.reload();
  await expect(page.locator('.desktop')).toHaveClass('desktop forest');
  await page.getByRole('button', { name: 'Launchpad', exact: true }).click();
  await page.getByLabel('Search applications').fill('Terminal');
  await expect(page.locator('.application-grid button')).toHaveCount(1);
});

test('mobile desktop keeps content and controls within the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/desktop.html');
  await page.getByRole('button', { name: 'About Connor', exact: true }).first().click();
  await expect(page.locator('.app-window')).toHaveClass(/maximized/);
  const box = await page.locator('.app-window').boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width).toBeLessThanOrEqual(390);
  await page.getByRole('button', { name: 'Contact', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Open email draft' })).toBeVisible();
  await page.screenshot({ path: 'test-results/mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
});

test('Notes organizes projects, social links, and the actual résumé', async ({ page }) => {
  await page.goto('/desktop.html');
  await expect(page.locator('.document-shortcuts')).toHaveCount(0);
  await page.getByRole('button', {name: 'Notes', exact: true}).click();
  const notes = page.getByRole('dialog', {name:'Notes',exact:true});
  await notes.getByRole('button', {name:/Social links Find me/}).click();
  await expect(notes.getByRole('link',{name:'GitHub'})).toHaveAttribute('href','https://github.com/loveconnor');
  await notes.getByRole('button',{name:/Projects HonestUI/}).click();
  await notes.getByRole('button',{name:'HonestUI Design & development',exact:true}).click();
  await expect(notes.getByRole('link',{name:'View HonestUI'})).toBeVisible();
  await notes.getByRole('textbox',{name:'Search notes'}).fill('Résumé');
  await expect(notes.getByRole('heading',{name:'Résumé',exact:true})).toBeVisible();
  await notes.getByRole('button',{name:/Résumé.pdf/}).click();
  const reader=page.getByRole('dialog',{name:'Connor Love résumé',exact:true});
  await expect(reader).toBeVisible();
  await expect(reader.locator('.held-paper img')).toHaveAttribute('src','/resume/preview.png');
  await expect(reader.locator('iframe')).toHaveCount(0);
  await reader.getByRole('button',{name:'Zoom in',exact:true}).click();
  await expect(reader).toHaveClass(/zoomed/);
  const pdf=await page.request.get('/resume/resume.pdf');
  expect(pdf.ok()).toBeTruthy();
  expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');
  await reader.getByRole('button',{name:'Close document'}).click();
  await expect(reader).toHaveCount(0);
  await notes.getByRole('textbox',{name:'Search notes'}).fill('not-a-note');
  await expect(notes.getByRole('heading',{name:'No notes found'})).toBeVisible();
});

test('Music shows the curated work playlist and selects previews', async ({ page }) => {
  await page.goto('/desktop.html');
  await page.getByRole('button', {name:'Music',exact:true}).click();
  const music=page.getByRole('dialog',{name:'Music',exact:true});
  await expect(music.getByRole('heading',{name:'Quiet Hours'})).toBeVisible();
  await expect(music.locator('.music-track')).toHaveCount(40);
  await expect(music.locator('.playlist-photo')).toHaveJSProperty('naturalWidth', 1254);
  const artists=await music.locator('.track-meta small').allTextContents();
  expect(new Set(artists).size).toBeGreaterThanOrEqual(20);
  expect(artists).toEqual(expect.arrayContaining(['Ricci Paolo','Newport','Shaboozey','Coldplay']));
  expect(artists.some(a=>/Harry Styles|Ed Sheeran|James Bay|Shawn Mendes|Jenna Raine|Livingston|Benson Boone|Josiah Queen|Julia Poe/.test(a))).toBe(false);
  await music.getByRole('button',{name:'Preview These Are The Days by Mark Ambor',exact:true}).click();
  await expect(music.locator('audio')).toHaveAttribute('src',/^https:\/\//);
  await expect(music.locator('.now-playing')).toContainText('These Are The Days');
  await expect(music.getByRole('link',{name:'Open These Are The Days in Apple Music',exact:true})).toHaveAttribute('href',/^https:\/\/music.apple.com\//);
});
