import assert from 'node:assert/strict';
import * as THREE from 'three';
import PaperPhysics from '../src/Application/World/PaperPhysics.ts';
const paper = new PaperPhysics();
const position = new THREE.Vector3(0, 500, 0);
const rotation = new THREE.Quaternion().setFromEuler(new THREE.Euler(-Math.PI / 2, 0, 0));
paper.reset(position);
for (let i = 0; i < 120; i++) paper.step(1/120, position, rotation);
const bend = Math.max(...paper.points.map(p => Math.abs(p.z)));
const stretch = Math.max(...paper.constraints.filter(c => c.stiffness === 1).map(c => Math.abs(paper.points[c.a].distanceTo(paper.points[c.b]) / c.length - 1)));
assert(bend > 5 && bend < 150, 'The unsupported sheet bends, without collapsing');
assert(stretch < .02, 'Paper resists stretching');
for (let i = 0; i < 120; i++) paper.step(1/120, position, rotation, 1);
assert(Math.max(...paper.points.map(p => Math.abs(p.z))) < 1, 'The reading pose settles');
position.y = 3;
paper.reset(position);
for (let i = 0; i < 90; i++) paper.step(1/60, position, rotation, 0, true);
assert(paper.points.every(p => p.clone().applyQuaternion(rotation).add(position).y >= 2.999), 'Desktop collision prevents penetration');
console.log('Paper physics: bending, stretch resistance, settling, and contact passed.');
