import { test, expect } from '@playwright/test';

test('ScreenBar controls change the lamp, leave auto mode, and retain settings', async ({ page }) => {
  test.setTimeout(150000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const model = page.waitForResponse(r => r.url().endsWith('/models/screenbar/original-screenbar.glb'));
  await page.goto('/');
  expect((await model).ok()).toBe(true);
  const start = page.getByRole('button', { name: 'START', exact: true });
  await expect(start).toBeEnabled({ timeout: 60000 });
  await start.click();
  await page.getByRole('button', { name: 'Lights', exact: true }).click({ timeout: 30000 });
  const controls = page.getByRole('region', { name: 'Lights', exact: true });
  await expect(controls).toBeVisible();
  const brightness = page.getByRole('slider', { name: 'ScreenBar brightness' });
  const temperature = page.getByRole('slider', { name: 'ScreenBar color temperature' });
  await brightness.focus();
  await brightness.press('End');
  await temperature.focus();
  await temperature.press('Home');
  await expect(temperature).toHaveAttribute('aria-valuetext', '2700 K');
  await controls.getByRole('button', { name: 'Light on', exact: true }).click();
  await expect(brightness).toBeDisabled();
  await controls.getByRole('button', { name: 'Light off', exact: true }).click();
  await expect(brightness).toHaveValue('15');
  await expect(temperature).toHaveValue('0');
  const auto = controls.getByRole('button', { name: 'Auto dimming' });
  await auto.click();
  await expect(auto).toHaveAttribute('aria-pressed', 'true');
  await temperature.focus();
  await temperature.press('End');
  await expect(auto).toHaveAttribute('aria-pressed', 'false');
  await expect(temperature).toHaveAttribute('aria-valuetext', '6500 K');
  await brightness.focus();
  await brightness.press('Home');
  await brightness.press('ArrowRight');
  await brightness.press('ArrowRight');
  await page.reload();
  await expect(start).toBeEnabled({ timeout: 60000 });
  await start.click();
  await page.getByRole('button', { name: 'Lights', exact: true }).click({ timeout: 30000 });
  await expect(brightness).toHaveValue('3');
  await expect(temperature).toHaveValue('7');
  expect(errors).toEqual([]);
});
