import { profile } from "../../desktop/profile";
export const roomNotes = [
  {
    title: profile.name,
    subtitle: "ABOUT ME",
    body: `${profile.role} based in ${profile.location}. I design and build websites, product interfaces, and interactive 3D experiences. My work brings frontend development, motion, performance, and accessibility together.`,
    lines: ["Freelance web", "developer", "Columbus, Ohio"],
  },
  {
    title: "What I work with",
    subtitle: "TOOLKIT",
    body: profile.skills.join(" · "),
    lines: ["React · Next.js", "TypeScript", "Three.js"],
  },
  ...profile.projects.map((p, i) => ({
    title: p.name,
    subtitle: "PROJECT",
    projectSlug: p.slug,
    body: [
      "A React component library with editable source code. Copy components into your project and make them your own. Includes interface controls, charts, icons, and optional visual effects.",
      "A color workbench for designers and developers. Build palettes, create light and dark themes, check contrast, and export CSS, Tailwind, or design tokens. Saved palettes stay in your browser.",
      "Compare how ten tokenizers split and count text. Inspect token boundaries side by side, try multilingual examples, and explore reproducible benchmarks. Text processing runs locally in a browser worker.",
    ][i],
    lines: [p.name, p.category],
    href: `${profile.website}/projects/${p.slug}`,
  })),
  {
    title: "Find me online",
    subtitle: "SAY HELLO",
    body: `${profile.email}\n${profile.github}\n${profile.linkedin}`,
    lines: ["Let's make", "something good.", "connorlove.com"],
  },
];
// A curated shelf of programming, interface design, and creative biography.
export const roomBooks = [
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    color: "#777a74",
    topic:
      "The biography of Apple's cofounder: creativity, product thinking, and the intersection of technology and design.",
    url: "https://www.simonandschuster.com/books/Steve-Jobs/Walter-Isaacson/9781982176860",
  },
  {
    title: "The Design of Everyday Things",
    author: "Don Norman",
    color: "#c29b64",
    topic:
      "Human-centered design, clear feedback, and making objects understandable.",
  },
  {
    title: "Don't Make Me Think",
    author: "Steve Krug",
    color: "#98614c",
    topic: "Usability and making websites feel intuitive.",
  },
  {
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    color: "#42625e",
    topic: "Practical habits for building and maintaining software.",
  },
  {
    title: "Refactoring",
    author: "Martin Fowler",
    color: "#516175",
    topic:
      "Improving the structure of existing code while preserving its behavior.",
  },
  {
    title: "Designing Web Interfaces",
    author: "Bill Scott & Theresa Neil",
    color: "#8d966d",
    topic: "Interaction patterns for responsive, usable web interfaces.",
    url: "https://www.oreilly.com/library/view/designing-web-interfaces/9780596155353/",
  },
  {
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    color: "#b7a77d",
    topic: "Programming fundamentals and expressive JavaScript.",
  },
  {
    title: "JavaScript: The Definitive Guide",
    author: "David Flanagan",
    color: "#546f89",
    topic: "A comprehensive guide to the language and browser APIs.",
    url: "https://www.oreilly.com/library/view/javascript-the-definitive/9781449393854/",
  },
  {
    title: "Thinking with Type",
    author: "Ellen Lupton",
    color: "#a85045",
    topic: "Typography, hierarchy, and how text shapes a design.",
  },
  {
    title: "Designing Interfaces",
    author: "Jenifer Tidwell",
    color: "#668078",
    topic: "Patterns for structuring clear user interfaces.",
  },
  {
    title: "The Elements of Typographic Style",
    author: "Robert Bringhurst",
    color: "#746850",
    topic:
      "Typographic principles, proportion, and the craft of readable pages.",
  },
  {
    title: "A Pattern Language",
    author: "Christopher Alexander",
    color: "#344d59",
    topic: "A Pattern Language — Christopher Alexander",
  },
  {
    title: "The Timeless Way of Building",
    author: "Christopher Alexander",
    color: "#b76946",
    topic: "The Timeless Way of Building — Christopher Alexander",
  },
  {
    title: "The Architecture of Happiness",
    author: "Alain de Botton",
    color: "#b9ac86",
    topic: "The Architecture of Happiness — Alain de Botton",
  },
  {
    title: "Ways of Seeing",
    author: "John Berger",
    color: "#4c604d",
    topic: "Ways of Seeing — John Berger",
  },
  {
    title: "Interaction of Color",
    author: "Josef Albers",
    color: "#783e3c",
    topic: "Interaction of Color — Josef Albers",
  },
  {
    title: "The Elements of Color",
    author: "Johannes Itten",
    color: "#d8ccb2",
    topic: "The Elements of Color — Johannes Itten",
  },
  {
    title: "Grid Systems in Graphic Design",
    author: "Josef Müller-Brockmann",
    color: "#383b41",
    topic: "Grid Systems in Graphic Design — Josef Müller-Brockmann",
  },
  {
    title: "The Visual Display of Quantitative Information",
    author: "Edward Tufte",
    color: "#a58950",
    topic: "The Visual Display of Quantitative Information — Edward Tufte",
  },
  {
    title: "Envisioning Information",
    author: "Edward Tufte",
    color: "#607b83",
    topic: "Envisioning Information — Edward Tufte",
  },
  {
    title: "Beautiful Evidence",
    author: "Edward Tufte",
    color: "#344d59",
    topic: "Beautiful Evidence — Edward Tufte",
  },
  {
    title: "Universal Principles of Design",
    author: "William Lidwell, Kritina Holden & Jill Butler",
    color: "#b76946",
    topic:
      "Universal Principles of Design — William Lidwell, Kritina Holden & Jill Butler",
  },
  {
    title: "About Face",
    author: "Alan Cooper et al.",
    color: "#b9ac86",
    topic: "About Face — Alan Cooper et al.",
  },
  {
    title: "The Humane Interface",
    author: "Jef Raskin",
    color: "#4c604d",
    topic: "The Humane Interface — Jef Raskin",
  },
  {
    title: "Designing for Emotion",
    author: "Aarron Walter",
    color: "#783e3c",
    topic: "Designing for Emotion — Aarron Walter",
  },
  {
    title: "Just Enough Research",
    author: "Erika Hall",
    color: "#d8ccb2",
    topic: "Just Enough Research — Erika Hall",
  },
  {
    title: "Articulating Design Decisions",
    author: "Tom Greever",
    color: "#383b41",
    topic: "Articulating Design Decisions — Tom Greever",
  },
  {
    title: "Creative Selection",
    author: "Ken Kocienda",
    color: "#a58950",
    topic: "Creative Selection — Ken Kocienda",
  },
  {
    title: "Shape Up",
    author: "Ryan Singer",
    color: "#607b83",
    topic: "Shape Up — Ryan Singer",
  },
  {
    title: "Rework",
    author: "Jason Fried & David Heinemeier Hansson",
    color: "#344d59",
    topic: "Rework — Jason Fried & David Heinemeier Hansson",
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    color: "#b76946",
    topic: "Deep Work — Cal Newport",
  },
  {
    title: "A Philosophy of Software Design",
    author: "John Ousterhout",
    color: "#b9ac86",
    topic: "A Philosophy of Software Design — John Ousterhout",
  },
  {
    title: "Working Effectively with Legacy Code",
    author: "Michael Feathers",
    color: "#4c604d",
    topic: "Working Effectively with Legacy Code — Michael Feathers",
  },
  {
    title: "Code Complete",
    author: "Steve McConnell",
    color: "#783e3c",
    topic: "Code Complete — Steve McConnell",
  },
  {
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    color: "#d8ccb2",
    topic: "The Mythical Man-Month — Frederick P. Brooks Jr.",
  },
  {
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson & Gerald Jay Sussman",
    color: "#383b41",
    topic:
      "Structure and Interpretation of Computer Programs — Harold Abelson & Gerald Jay Sussman",
  },
  {
    title: "Grokking Algorithms",
    author: "Aditya Bhargava",
    color: "#a58950",
    topic: "Grokking Algorithms — Aditya Bhargava",
  },
  {
    title: "You Don’t Know JS Yet: Get Started",
    author: "Kyle Simpson",
    color: "#607b83",
    topic: "You Don’t Know JS Yet: Get Started — Kyle Simpson",
  },
  {
    title: "CSS Secrets",
    author: "Lea Verou",
    color: "#344d59",
    topic: "CSS Secrets — Lea Verou",
  },
  {
    title: "HTML & CSS",
    author: "Jon Duckett",
    color: "#b76946",
    topic: "HTML & CSS — Jon Duckett",
  },
  {
    title: "Responsive Web Design",
    author: "Ethan Marcotte",
    color: "#b9ac86",
    topic: "Responsive Web Design — Ethan Marcotte",
  },
  {
    title: "The Nature of Code",
    author: "Daniel Shiffman",
    color: "#4c604d",
    topic: "The Nature of Code — Daniel Shiffman",
  },
  {
    title: "The Creative Act",
    author: "Rick Rubin",
    color: "#783e3c",
    topic: "The Creative Act — Rick Rubin",
  },
  {
    title: "Steal Like an Artist",
    author: "Austin Kleon",
    color: "#d8ccb2",
    topic: "Steal Like an Artist — Austin Kleon",
  },
  {
    title: "The War of Art",
    author: "Steven Pressfield",
    color: "#383b41",
    topic: "The War of Art — Steven Pressfield",
  },
  {
    title: "On Writing",
    author: "Stephen King",
    color: "#a58950",
    topic: "On Writing — Stephen King",
  },
  {
    title: "Bird by Bird",
    author: "Anne Lamott",
    color: "#607b83",
    topic: "Bird by Bird — Anne Lamott",
  },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    color: "#344d59",
    topic: "The Little Prince — Antoine de Saint-Exupéry",
  },
];
